version: '3'
services:
  colmar-nginx:
    image: trzl/portfolio:colmar-react.1
    container_name: colmar-nginx
    restart: unless-stopped
  reverseproxy:
    image: trzl/portfolio:colmar-proxy.1
    container_name: colmar-proxy
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    depends_on:
      - colmar-nginx
    environment:
      VIRTUAL_HOST: colmar.tbrownkcdev.com
      LETSENCRYPT_HOST: colmar.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy