version: '3'
services:
  react-nginx:
    image: trzl/portfolio:colmar-react.1
    restart: unless-stopped
    container_name: colmar-nginx
    networks:
      - colmar
    env_file: .env
    environment:
      - NODE_ENV=production
  reverseproxy:
    image: trzl/portfolio:colmar-proxy.1
    container_name: colmar-proxy
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    depends_on:
      - react-nginx
   environment:
      VIRTUAL_HOST: colmarg.tbrownkcdev.com
      LETSENCRYPT_HOST: colmarg.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
  colmar:
    driver: bridge